server:
  port: 8081

twilio:
  account_sid: AC0aa94b1bc61266de346803ac86371970
  auth_token:  9a4f67b585936770f8cedb260adb3e58
  trial_number: +19034209311
  
spring:
  jpa:
    open-in-view: 'true'
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: 'true'
  datasource:
    username: sa
    url: jdbc:h2:mem:sms
    driverClassName: org.h2.Driver
    password: password
    
    